### ISSUE TITLE
Comfyui v0.11.0 error

### ISSUE THREAD

**Issue by Cloudreadypc** [1038lab/ComfyUI-QwenVL#123]
Error loading module AILab_QwenVL: cannot import name 'AutoModelForVision2Seq' from 'transformers' (D:\AI\StabilityMatrix\Data\Packages\ComfyUI\venv\Lib\site-packages\transformers\__init__.py)
Error loading module AILab_QwenVL_PromptEnhancer: cannot import name 'ATTENTION_MODES' from 'AILab_QwenVL' (D:\AI\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-QwenVL\AILab_QwenVL.py)

Python version: 3.12.10
pytorch version: 2.10.0+cu130

Error occurs after updating Comfyui to v0.11.0. Thanks.

**Comment by NeonLightning** [comment]
same error here

**Comment by NeonLightning** [comment]
pip install --upgrade transformers==4.57.1

**Comment by NeonLightning** [comment]
hrm doesn't error anymore but still doesn't load
